FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .
RUN npx prisma generate

EXPOSE 4000
CMD ["sh", "-c", "node src/index.js & npx prisma migrate deploy; wait -n"]